### ISSUE TITLE
Slight issue with readme

### ISSUE THREAD

**Issue by zigon15** [smunaut/openlane-baremetal#1]
Under README.md -> Install the tools
`source ${HOME}/sky130/openlane-workspace/env.sh` should be `source ${HOME}/sky130/openlane_workspace/env.sh` I believe.
![image](https://user-images.githubusercontent.com/16912854/91256177-cb05da80-e7a5-11ea-9eca-7c1e1cc9349e.png)

The created _openlane-baremetal_ directory has a - though so maybe the workspace should also use a - separator as well though?

**Comment by smunaut** [comment]
Ooops, I never saw any notification for that issue, sorry for the delay.
Will be fixed shortly.  The inconsistency will stay though ... I think the repo should have used `_` since that's what's used everywhere in openlane ... oh well.
